export const moduleConfigs = {
  // plants: {
  //   title: "Plant Master",
  //   path: "/masters/plants",
  //   apiGroup: "masters",
  //   moduleName: "plants",
  //   idField: "PlantID",
  //   columns: ["PlantCode", "PlantName", "City", "State", "IsActive"],
  // },
  // vehicleTypes: {
  //   title: "Vehicle Types",
  //   path: "/masters/vehicle-types",
  //   apiGroup: "masters",
  //   moduleName: "vehicle-types",
  //   idField: "VehicleTypeID",
  //   columns: ["VehicleName", "Capacity", "Unit"],
  // },
  // weights: {
  //   title: "Weight Master",
  //   path: "/masters/weights",
  //   apiGroup: "masters",
  //   moduleName: "weights",
  //   idField: "WeightID",
  //   columns: ["FromWeight", "ToWeight", "WeightUnit"],
  // },
  // destinations: {
  //   title: "Destination Master",
  //   path: "/masters/destinations",
  //   apiGroup: "masters",
  //   moduleName: "destinations",
  //   idField: "DestinationID",
  //   columns: ["City", "District", "State", "Pincode"],
  // },
  // statuses: {
  //   title: "Status Master",
  //   path: "/masters/statuses",
  //   apiGroup: "masters",
  //   moduleName: "statuses",
  //   idField: "StatusID",
  //   columns: ["StatusName", "ModuleName"],
  // },

  contracts: {
    title: "Contract Master",
    path: "/contracts",
    apiGroup: "contracts",
    moduleName: "",
    stateKey: "contracts",
    idField: "ContractID",
    addPath: "/contracts/add",
    addButtonText: "Add Contract",
    columns: [
      "ContractNo",
      "VendorID",
      "PlantID",
      "ContractStartDate",
      "ContractEndDate",
      "Status",
    ],
  },
  invoices: {
    title: "Invoices",
    path: "/invoices",
    apiGroup: "invoices",
    moduleName: "invoices",
    idField: "InvoiceID",
    columns: [
      "InvoiceNumber",
      "InvoiceDate",
      "VendorID",
      "PlantID",
      "TotalInvoiceAmount",
      "InvoiceStatusID",
    ],
  },
  // Added Settings Module configuration for Admin
  settings: {
    title: "Settings & Hierarchy",
    path: "/admin/settings",
    apiGroup: "settings",
    moduleName: "settings",
    idField: "ConfigID",
    columns: [
      "CompanyID",
      "SBUID",
      "PlantHierarchyID",
      "LocationID",
      "PrimaryUserID",
    ],
  },
  // verifications: {
  //   title: "Invoice Verification",
  //   path: "/workflows/verifications",
  //   apiGroup: "workflows",
  //   moduleName: "verifications",
  //   idField: "VerificationID",
  //   columns: [
  //     "InvoiceID",
  //     "ContractID",
  //     "ExpectedAmount",
  //     "InvoiceAmount",
  //     "DifferenceAmount",
  //     "VerificationStatus",
  //   ],
  // },
  // approvals: {
  //   title: "Invoice Approvals",
  //   path: "/workflows/approvals",
  //   apiGroup: "workflows",
  //   moduleName: "approvals",
  //   idField: "ApprovalID",
  //   columns: ["InvoiceID", "ApprovedBy", "StatusID", "ApprovedDate", "Remarks"],
  // },
  // audits: {
  //   title: "Audit Logs",
  //   path: "/workflows/audits",
  //   apiGroup: "workflows",
  //   moduleName: "audits",
  //   idField: "AuditID",
  //   columns: ["UserID", "TableName", "RecordID", "ActionType", "ActionDate"],
  // },
  // emails: {
  //   title: "Email Logs",
  //   path: "/workflows/emails",
  //   apiGroup: "workflows",
  //   moduleName: "emails",
  //   idField: "EmailLogID",
  //   columns: ["RecipientEmail", "Subject", "Status", "SentAt"],
  // },

};

export const moduleNavigation = [
  moduleConfigs.contracts,
  moduleConfigs.invoices,
  moduleConfigs.settings, // Added here to reflect in navigation/sidebar
];