export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  VENDORS: "/vendors",
  PLANTS: "/masters/plants",
  VEHICLE_TYPES: "/masters/vehicle-types",
  WEIGHTS: "/masters/weights",
  DESTINATIONS: "/masters/destinations",
  STATUSES: "/masters/statuses",
  CONTRACTS: "/contracts",
  INVOICES: "/invoices",
  SETTING: "/setting",
};
